package org.jbpm.comvivapoc;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(f080885edfbc1ca1d5e827f994234ffd)
 */
@org.kie.api.definition.type.Label(value = "Pack List")
public class PackList  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "List of Packs")
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.List<org.jbpm.comvivapoc.Pack> listOfPacks;

    public PackList() {
    }

    public PackList(java.util.List<org.jbpm.comvivapoc.Pack> listOfPacks) {
        this.listOfPacks = listOfPacks;
    }


    
    public java.util.List<org.jbpm.comvivapoc.Pack> getListOfPacks() {
        return this.listOfPacks;
    }

    public void setListOfPacks(java.util.List<org.jbpm.comvivapoc.Pack> listOfPacks) {
        this.listOfPacks = listOfPacks;
    }
}