package org.jbpm.comvivapoc;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(c37e016742797f40c6c5dc7243481d3d)
 */
@org.kie.api.definition.type.Label(value = "Pack")
public class Pack  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Amount")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String amount;
    
    @org.kie.api.definition.type.Label(value = "Pack Desc")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String packDesc;
    
    @org.kie.api.definition.type.Label(value = "Pack ID")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String packID;
    
    @org.kie.api.definition.type.Label(value = "Pack No")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String packNo;
    
    @org.kie.api.definition.type.Label(value = "Validity")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String validity;

    public Pack() {
    }

    public Pack(java.lang.String packNo, java.lang.String packID, java.lang.String packDesc, java.lang.String validity, java.lang.String amount) {
        this.packNo = packNo;
        this.packID = packID;
        this.packDesc = packDesc;
        this.validity = validity;
        this.amount = amount;
    }


    
    public java.lang.String getAmount() {
        return this.amount;
    }

    public void setAmount(java.lang.String amount) {
        this.amount = amount;
    }
    
    public java.lang.String getPackDesc() {
        return this.packDesc;
    }

    public void setPackDesc(java.lang.String packDesc) {
        this.packDesc = packDesc;
    }
    
    public java.lang.String getPackID() {
        return this.packID;
    }

    public void setPackID(java.lang.String packID) {
        this.packID = packID;
    }
    
    public java.lang.String getPackNo() {
        return this.packNo;
    }

    public void setPackNo(java.lang.String packNo) {
        this.packNo = packNo;
    }
    
    public java.lang.String getValidity() {
        return this.validity;
    }

    public void setValidity(java.lang.String validity) {
        this.validity = validity;
    }
}